### ISSUE TITLE
Small bug with drawaCard function

### ISSUE THREAD

**Issue by bjsi** [esrever10/remnote-plugin-roaming#1]
https://github.com/esrever10/remnote-plugin-roaming/blob/7ccaeb89a03130b7a9dca613733433b3253653c7/src/widgets/roaming_widget.tsx#L196-L212

If Rem is not found, it still returns the Rem, so it is possible to navigate to a Rem which fails the block check.

**Comment by esrever10** [comment]
Try 50 times to find a useable rem. It's enough, if can't found, it will return a nonempty rem, but maybe a remnote built-in rem，like a built-in powerup slot and so on.
