### ISSUE TITLE
Calling rem.getAll every time user clicks the block/roam buttons

### ISSUE THREAD

**Issue by bjsi** [esrever10/remnote-plugin-roaming#2]
https://github.com/esrever10/remnote-plugin-roaming/blob/7ccaeb89a03130b7a9dca613733433b3253653c7/src/widgets/roaming_widget.tsx#L168-L169

Calling `rem.getAll` every time user clicks the block/roam buttons might be slow for users with large KBs because it has to load all of the Rem in the user's knowledge base and serialize them and send to the plugin. 

I think it's okay for now, but if users complain that it is slow, you could instead only set the total once when the widget first loads?

**Comment by esrever10** [comment]
Nice suggestion.I will improve it.
